/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI_slave.h"
#include "SPI_slave_PVT.h"
#include "mosi_aliases.h"
#include "mosi.h"
#include "sclk_aliases.h"
#include "sclk.h"
#include "ss_aliases.h"
#include "ss.h"
#include "miso_aliases.h"
#include "miso.h"
#include "slave_rx_interrupt.h"
#include "LED_pin_aliases.h"
#include "LED_pin.h"
#include "UART_rx_interrupt.h"
#include "UART_1.h"
#include "isr_wheel_tick.h"
#include "WheelTickPin_aliases.h"
#include "WheelTickPin.h"
#include "timer_clock_3.h"
#include "MotorLockTimer.h"
#include "Timer_Isr_BikeIsStopping.h"
#include "AccelerometerTimer.h"
#include "timer_clock_2.h"
#include "isr_bike_stopped.h"
#include "isr_bike_is_idle.h"
#include "isr_bike_is_moving.h"
#include "Pin_1_ac_idle_aliases.h"
#include "Pin_1_ac_idle.h"
#include "Pin_2_ac_moving_aliases.h"
#include "Pin_2_ac_moving.h"
#include "In_1_aliases.h"
#include "In_1.h"
#include "In_2_aliases.h"
#include "In_2.h"
#include "EA_aliases.h"
#include "EA.h"
#include "isr_bikelock.h"
#include "Timer_clock_1.h"
#include "WheelTickTimer.h"
#include "SPI_slave_IntClock.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

